/*
 * This file is generated by jOOQ.
 */
package com.talendorse.server.model.tables;


import com.talendorse.server.model.Database;
import com.talendorse.server.model.Indexes;
import com.talendorse.server.model.Keys;
import com.talendorse.server.model.tables.records.LanguagesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Languages extends TableImpl<LanguagesRecord> {

    private static final long serialVersionUID = -333991960;

    /**
     * The reference instance of <code>database.languages</code>
     */
    public static final Languages LANGUAGES = new Languages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LanguagesRecord> getRecordType() {
        return LanguagesRecord.class;
    }

    /**
     * The column <code>database.languages.id_language</code>.
     */
    public final TableField<LanguagesRecord, Integer> ID_LANGUAGE = createField("id_language", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>database.languages.name</code>.
     */
    public final TableField<LanguagesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>database.languages.date_created</code>.
     */
    public final TableField<LanguagesRecord, Timestamp> DATE_CREATED = createField("date_created", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>database.languages</code> table reference
     */
    public Languages() {
        this(DSL.name("languages"), null);
    }

    /**
     * Create an aliased <code>database.languages</code> table reference
     */
    public Languages(String alias) {
        this(DSL.name(alias), LANGUAGES);
    }

    /**
     * Create an aliased <code>database.languages</code> table reference
     */
    public Languages(Name alias) {
        this(alias, LANGUAGES);
    }

    private Languages(Name alias, Table<LanguagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Languages(Name alias, Table<LanguagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Languages(Table<O> child, ForeignKey<O, LanguagesRecord> key) {
        super(child, key, LANGUAGES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Database.DATABASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LANGUAGES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<LanguagesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_LANGUAGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LanguagesRecord> getPrimaryKey() {
        return Keys.KEY_LANGUAGES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LanguagesRecord>> getKeys() {
        return Arrays.<UniqueKey<LanguagesRecord>>asList(Keys.KEY_LANGUAGES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Languages as(String alias) {
        return new Languages(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Languages as(Name alias) {
        return new Languages(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Languages rename(String name) {
        return new Languages(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Languages rename(Name name) {
        return new Languages(name, null);
    }
}
