/*
 * This file is generated by jOOQ.
 */
package com.talendorse.server.model.tables;


import com.talendorse.server.model.Database;
import com.talendorse.server.model.Indexes;
import com.talendorse.server.model.Keys;
import com.talendorse.server.model.tables.records.LogsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Logs extends TableImpl<LogsRecord> {

    private static final long serialVersionUID = -665359954;

    /**
     * The reference instance of <code>database.logs</code>
     */
    public static final Logs LOGS = new Logs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LogsRecord> getRecordType() {
        return LogsRecord.class;
    }

    /**
     * The column <code>database.logs.id_log</code>.
     */
    public final TableField<LogsRecord, Integer> ID_LOG = createField("id_log", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>database.logs.tag</code>.
     */
    public final TableField<LogsRecord, String> TAG = createField("tag", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>database.logs.log</code>.
     */
    public final TableField<LogsRecord, String> LOG = createField("log", org.jooq.impl.SQLDataType.VARCHAR(11844), this, "");

    /**
     * The column <code>database.logs.date_created</code>.
     */
    public final TableField<LogsRecord, Timestamp> DATE_CREATED = createField("date_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>database.logs</code> table reference
     */
    public Logs() {
        this(DSL.name("logs"), null);
    }

    /**
     * Create an aliased <code>database.logs</code> table reference
     */
    public Logs(String alias) {
        this(DSL.name(alias), LOGS);
    }

    /**
     * Create an aliased <code>database.logs</code> table reference
     */
    public Logs(Name alias) {
        this(alias, LOGS);
    }

    private Logs(Name alias, Table<LogsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Logs(Name alias, Table<LogsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Logs(Table<O> child, ForeignKey<O, LogsRecord> key) {
        super(child, key, LOGS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Database.DATABASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LOGS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<LogsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_LOGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LogsRecord> getPrimaryKey() {
        return Keys.KEY_LOGS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LogsRecord>> getKeys() {
        return Arrays.<UniqueKey<LogsRecord>>asList(Keys.KEY_LOGS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Logs as(String alias) {
        return new Logs(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Logs as(Name alias) {
        return new Logs(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Logs rename(String name) {
        return new Logs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Logs rename(Name name) {
        return new Logs(name, null);
    }
}
