/*
 * This file is generated by jOOQ.
 */
package com.talendorse.server.model.tables.records;


import com.talendorse.server.model.tables.Referrals;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferralsRecord extends UpdatableRecordImpl<ReferralsRecord> implements Record13<Integer, Integer, Integer, Integer, Integer, String, Integer, String, String, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -645177324;

    /**
     * Setter for <code>database.referrals.id_referral</code>.
     */
    public void setIdReferral(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>database.referrals.id_referral</code>.
     */
    public Integer getIdReferral() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>database.referrals.id_endorser</code>.
     */
    public void setIdEndorser(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>database.referrals.id_endorser</code>.
     */
    public Integer getIdEndorser() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>database.referrals.id_candidate</code>.
     */
    public void setIdCandidate(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>database.referrals.id_candidate</code>.
     */
    public Integer getIdCandidate() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>database.referrals.score</code>.
     */
    public void setScore(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>database.referrals.score</code>.
     */
    public Integer getScore() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>database.referrals.state</code>.
     */
    public void setState(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>database.referrals.state</code>.
     */
    public Integer getState() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>database.referrals.code</code>.
     */
    public void setCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>database.referrals.code</code>.
     */
    public String getCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>database.referrals.id_offer</code>.
     */
    public void setIdOffer(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>database.referrals.id_offer</code>.
     */
    public Integer getIdOffer() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>database.referrals.email_candidate</code>.
     */
    public void setEmailCandidate(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>database.referrals.email_candidate</code>.
     */
    public String getEmailCandidate() {
        return (String) get(7);
    }

    /**
     * Setter for <code>database.referrals.nameCandidate</code>.
     */
    public void setNamecandidate(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>database.referrals.nameCandidate</code>.
     */
    public String getNamecandidate() {
        return (String) get(8);
    }

    /**
     * Setter for <code>database.referrals.description</code>.
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>database.referrals.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    /**
     * Setter for <code>database.referrals.relation</code>.
     */
    public void setRelation(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>database.referrals.relation</code>.
     */
    public Integer getRelation() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>database.referrals.date_creation</code>.
     */
    public void setDateCreation(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>database.referrals.date_creation</code>.
     */
    public Timestamp getDateCreation() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>database.referrals.date_accepted</code>.
     */
    public void setDateAccepted(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>database.referrals.date_accepted</code>.
     */
    public Timestamp getDateAccepted() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Integer, Integer, Integer, String, Integer, String, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Integer, Integer, Integer, String, Integer, String, String, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Referrals.REFERRALS.ID_REFERRAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Referrals.REFERRALS.ID_ENDORSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Referrals.REFERRALS.ID_CANDIDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Referrals.REFERRALS.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Referrals.REFERRALS.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Referrals.REFERRALS.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Referrals.REFERRALS.ID_OFFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Referrals.REFERRALS.EMAIL_CANDIDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Referrals.REFERRALS.NAMECANDIDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Referrals.REFERRALS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Referrals.REFERRALS.RELATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Referrals.REFERRALS.DATE_CREATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Referrals.REFERRALS.DATE_ACCEPTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdReferral();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdEndorser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getIdCandidate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getIdOffer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getEmailCandidate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getNamecandidate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getRelation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getDateAccepted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdReferral();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdEndorser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdCandidate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdOffer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getEmailCandidate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getNamecandidate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getRelation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getDateAccepted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value1(Integer value) {
        setIdReferral(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value2(Integer value) {
        setIdEndorser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value3(Integer value) {
        setIdCandidate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value4(Integer value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value5(Integer value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value6(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value7(Integer value) {
        setIdOffer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value8(String value) {
        setEmailCandidate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value9(String value) {
        setNamecandidate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value10(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value11(Integer value) {
        setRelation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value12(Timestamp value) {
        setDateCreation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value13(Timestamp value) {
        setDateAccepted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6, Integer value7, String value8, String value9, String value10, Integer value11, Timestamp value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReferralsRecord
     */
    public ReferralsRecord() {
        super(Referrals.REFERRALS);
    }

    /**
     * Create a detached, initialised ReferralsRecord
     */
    public ReferralsRecord(Integer idReferral, Integer idEndorser, Integer idCandidate, Integer score, Integer state, String code, Integer idOffer, String emailCandidate, String namecandidate, String description, Integer relation, Timestamp dateCreation, Timestamp dateAccepted) {
        super(Referrals.REFERRALS);

        set(0, idReferral);
        set(1, idEndorser);
        set(2, idCandidate);
        set(3, score);
        set(4, state);
        set(5, code);
        set(6, idOffer);
        set(7, emailCandidate);
        set(8, namecandidate);
        set(9, description);
        set(10, relation);
        set(11, dateCreation);
        set(12, dateAccepted);
    }
}
