/*
 * This file is generated by jOOQ.
 */
package com.talendorse.server.model.tables.records;


import com.talendorse.server.model.tables.UserLanguage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLanguageRecord extends UpdatableRecordImpl<UserLanguageRecord> implements Record5<Integer, Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -617303795;

    /**
     * Setter for <code>database.user_language.id_user_language</code>.
     */
    public void setIdUserLanguage(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>database.user_language.id_user_language</code>.
     */
    public Integer getIdUserLanguage() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>database.user_language.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>database.user_language.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>database.user_language.id_language</code>.
     */
    public void setIdLanguage(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>database.user_language.id_language</code>.
     */
    public Integer getIdLanguage() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>database.user_language.level</code>.
     */
    public void setLevel(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>database.user_language.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>database.user_language.date_created</code>.
     */
    public void setDateCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>database.user_language.date_created</code>.
     */
    public Timestamp getDateCreated() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserLanguage.USER_LANGUAGE.ID_USER_LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserLanguage.USER_LANGUAGE.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserLanguage.USER_LANGUAGE.ID_LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UserLanguage.USER_LANGUAGE.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserLanguage.USER_LANGUAGE.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdUserLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getIdLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdUserLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLanguageRecord value1(Integer value) {
        setIdUserLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLanguageRecord value2(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLanguageRecord value3(Integer value) {
        setIdLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLanguageRecord value4(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLanguageRecord value5(Timestamp value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLanguageRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserLanguageRecord
     */
    public UserLanguageRecord() {
        super(UserLanguage.USER_LANGUAGE);
    }

    /**
     * Create a detached, initialised UserLanguageRecord
     */
    public UserLanguageRecord(Integer idUserLanguage, Integer idUser, Integer idLanguage, Integer level, Timestamp dateCreated) {
        super(UserLanguage.USER_LANGUAGE);

        set(0, idUserLanguage);
        set(1, idUser);
        set(2, idLanguage);
        set(3, level);
        set(4, dateCreated);
    }
}
