/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model;


import com.jobster.server.model.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jobster
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jobster.users</code>.
     */
    public static final Users USERS = com.jobster.server.model.tables.Users.USERS;
}
