/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model.tables.records;


import com.jobster.server.model.tables.Education;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EducationRecord extends UpdatableRecordImpl<EducationRecord> implements Record8<Integer, String, Timestamp, Timestamp, String, String, String, Integer> {

    private static final long serialVersionUID = -1007841046;

    /**
     * Setter for <code>jobster.education.id_education</code>.
     */
    public void setIdEducation(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobster.education.id_education</code>.
     */
    public Integer getIdEducation() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobster.education.school-name</code>.
     */
    public void setSchoolName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobster.education.school-name</code>.
     */
    public String getSchoolName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jobster.education.start-date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobster.education.start-date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>jobster.education.end-date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>jobster.education.end-date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>jobster.education.degreee</code>.
     */
    public void setDegreee(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jobster.education.degreee</code>.
     */
    public String getDegreee() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jobster.education.activities</code>.
     */
    public void setActivities(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jobster.education.activities</code>.
     */
    public String getActivities() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jobster.education.notes</code>.
     */
    public void setNotes(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jobster.education.notes</code>.
     */
    public String getNotes() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jobster.education.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>jobster.education.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Timestamp, Timestamp, String, String, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Timestamp, Timestamp, String, String, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Education.EDUCATION.ID_EDUCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Education.EDUCATION.SCHOOL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Education.EDUCATION.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Education.EDUCATION.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Education.EDUCATION.DEGREEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Education.EDUCATION.ACTIVITIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Education.EDUCATION.NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Education.EDUCATION.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdEducation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSchoolName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDegreee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getActivities();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdEducation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSchoolName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDegreee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getActivities();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value1(Integer value) {
        setIdEducation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value2(String value) {
        setSchoolName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value3(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value4(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value5(String value) {
        setDegreee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value6(String value) {
        setActivities(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value7(String value) {
        setNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value8(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4, String value5, String value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EducationRecord
     */
    public EducationRecord() {
        super(Education.EDUCATION);
    }

    /**
     * Create a detached, initialised EducationRecord
     */
    public EducationRecord(Integer idEducation, String schoolName, Timestamp startDate, Timestamp endDate, String degreee, String activities, String notes, Integer idUser) {
        super(Education.EDUCATION);

        set(0, idEducation);
        set(1, schoolName);
        set(2, startDate);
        set(3, endDate);
        set(4, degreee);
        set(5, activities);
        set(6, notes);
        set(7, idUser);
    }
}
