/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model.tables.records;


import com.jobster.server.model.tables.Idioms;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IdiomsRecord extends UpdatableRecordImpl<IdiomsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 153205320;

    /**
     * Setter for <code>jobster.idioms.id_idiom</code>.
     */
    public void setIdIdiom(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobster.idioms.id_idiom</code>.
     */
    public Integer getIdIdiom() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobster.idioms.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobster.idioms.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Idioms.IDIOMS.ID_IDIOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Idioms.IDIOMS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdIdiom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdIdiom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdiomsRecord value1(Integer value) {
        setIdIdiom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdiomsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdiomsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IdiomsRecord
     */
    public IdiomsRecord() {
        super(Idioms.IDIOMS);
    }

    /**
     * Create a detached, initialised IdiomsRecord
     */
    public IdiomsRecord(Integer idIdiom, String name) {
        super(Idioms.IDIOMS);

        set(0, idIdiom);
        set(1, name);
    }
}
