/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model.tables.records;


import com.jobster.server.model.tables.Offers;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OffersRecord extends UpdatableRecordImpl<OffersRecord> implements Record8<Integer, String, String, String, String, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1963488862;

    /**
     * Setter for <code>jobster.offers.id_offer</code>.
     */
    public void setIdOffer(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobster.offers.id_offer</code>.
     */
    public Integer getIdOffer() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobster.offers.position</code>.
     */
    public void setPosition(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobster.offers.position</code>.
     */
    public String getPosition() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jobster.offers.summary</code>.
     */
    public void setSummary(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobster.offers.summary</code>.
     */
    public String getSummary() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jobster.offers.experience</code>.
     */
    public void setExperience(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jobster.offers.experience</code>.
     */
    public String getExperience() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jobster.offers.job_functions</code>.
     */
    public void setJobFunctions(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jobster.offers.job_functions</code>.
     */
    public String getJobFunctions() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jobster.offers.date_ini</code>.
     */
    public void setDateIni(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>jobster.offers.date_ini</code>.
     */
    public Timestamp getDateIni() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>jobster.offers.date_end</code>.
     */
    public void setDateEnd(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>jobster.offers.date_end</code>.
     */
    public Timestamp getDateEnd() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>jobster.offers.date_creation</code>.
     */
    public void setDateCreation(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>jobster.offers.date_creation</code>.
     */
    public Timestamp getDateCreation() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Offers.OFFERS.ID_OFFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Offers.OFFERS.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Offers.OFFERS.SUMMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Offers.OFFERS.EXPERIENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Offers.OFFERS.JOB_FUNCTIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Offers.OFFERS.DATE_INI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Offers.OFFERS.DATE_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Offers.OFFERS.DATE_CREATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdOffer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSummary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getExperience();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getJobFunctions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDateIni();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDateEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdOffer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSummary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getExperience();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getJobFunctions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDateIni();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDateEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffersRecord value1(Integer value) {
        setIdOffer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffersRecord value2(String value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffersRecord value3(String value) {
        setSummary(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffersRecord value4(String value) {
        setExperience(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffersRecord value5(String value) {
        setJobFunctions(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffersRecord value6(Timestamp value) {
        setDateIni(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffersRecord value7(Timestamp value) {
        setDateEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffersRecord value8(Timestamp value) {
        setDateCreation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffersRecord values(Integer value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OffersRecord
     */
    public OffersRecord() {
        super(Offers.OFFERS);
    }

    /**
     * Create a detached, initialised OffersRecord
     */
    public OffersRecord(Integer idOffer, String position, String summary, String experience, String jobFunctions, Timestamp dateIni, Timestamp dateEnd, Timestamp dateCreation) {
        super(Offers.OFFERS);

        set(0, idOffer);
        set(1, position);
        set(2, summary);
        set(3, experience);
        set(4, jobFunctions);
        set(5, dateIni);
        set(6, dateEnd);
        set(7, dateCreation);
    }
}
