/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model.tables.records;


import com.jobster.server.model.tables.Tokens;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokensRecord extends UpdatableRecordImpl<TokensRecord> implements Record6<Integer, String, Timestamp, Integer, Timestamp, String> {

    private static final long serialVersionUID = -1631810577;

    /**
     * Setter for <code>jobster.tokens.id_token</code>.
     */
    public void setIdToken(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobster.tokens.id_token</code>.
     */
    public Integer getIdToken() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobster.tokens.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobster.tokens.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jobster.tokens.expiration_date</code>.
     */
    public void setExpirationDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobster.tokens.expiration_date</code>.
     */
    public Timestamp getExpirationDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>jobster.tokens.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>jobster.tokens.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>jobster.tokens.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>jobster.tokens.creation_date</code>.
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>jobster.tokens.tokenscol</code>.
     */
    public void setTokenscol(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jobster.tokens.tokenscol</code>.
     */
    public String getTokenscol() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Timestamp, Integer, Timestamp, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Timestamp, Integer, Timestamp, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tokens.TOKENS.ID_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tokens.TOKENS.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Tokens.TOKENS.EXPIRATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Tokens.TOKENS.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Tokens.TOKENS.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Tokens.TOKENS.TOKENSCOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getExpirationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTokenscol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getExpirationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTokenscol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokensRecord value1(Integer value) {
        setIdToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokensRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokensRecord value3(Timestamp value) {
        setExpirationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokensRecord value4(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokensRecord value5(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokensRecord value6(String value) {
        setTokenscol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokensRecord values(Integer value1, String value2, Timestamp value3, Integer value4, Timestamp value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokensRecord
     */
    public TokensRecord() {
        super(Tokens.TOKENS);
    }

    /**
     * Create a detached, initialised TokensRecord
     */
    public TokensRecord(Integer idToken, String token, Timestamp expirationDate, Integer idUser, Timestamp creationDate, String tokenscol) {
        super(Tokens.TOKENS);

        set(0, idToken);
        set(1, token);
        set(2, expirationDate);
        set(3, idUser);
        set(4, creationDate);
        set(5, tokenscol);
    }
}
