/*
 * This file is generated by jOOQ.
 */
package com.talendorse.server.model;


import com.talendorse.server.model.tables.Companies;
import com.talendorse.server.model.tables.Countries;
import com.talendorse.server.model.tables.Education;
import com.talendorse.server.model.tables.Formations;
import com.talendorse.server.model.tables.Languages;
import com.talendorse.server.model.tables.OfferFormation;
import com.talendorse.server.model.tables.Offers;
import com.talendorse.server.model.tables.OffersSkills;
import com.talendorse.server.model.tables.Referrals;
import com.talendorse.server.model.tables.Skills;
import com.talendorse.server.model.tables.Tokens;
import com.talendorse.server.model.tables.UserFormation;
import com.talendorse.server.model.tables.UserLanguage;
import com.talendorse.server.model.tables.Users;
import com.talendorse.server.model.tables.UsersSkills;
import com.talendorse.server.model.tables.ViewsUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Database extends SchemaImpl {

    private static final long serialVersionUID = 1086606714;

    /**
     * The reference instance of <code>database</code>
     */
    public static final Database DATABASE = new Database();

    /**
     * The table <code>database.companies</code>.
     */
    public final Companies COMPANIES = com.talendorse.server.model.tables.Companies.COMPANIES;

    /**
     * The table <code>database.countries</code>.
     */
    public final Countries COUNTRIES = com.talendorse.server.model.tables.Countries.COUNTRIES;

    /**
     * The table <code>database.education</code>.
     */
    public final Education EDUCATION = com.talendorse.server.model.tables.Education.EDUCATION;

    /**
     * The table <code>database.formations</code>.
     */
    public final Formations FORMATIONS = com.talendorse.server.model.tables.Formations.FORMATIONS;

    /**
     * The table <code>database.languages</code>.
     */
    public final Languages LANGUAGES = com.talendorse.server.model.tables.Languages.LANGUAGES;

    /**
     * The table <code>database.offer_formation</code>.
     */
    public final OfferFormation OFFER_FORMATION = com.talendorse.server.model.tables.OfferFormation.OFFER_FORMATION;

    /**
     * The table <code>database.offers</code>.
     */
    public final Offers OFFERS = com.talendorse.server.model.tables.Offers.OFFERS;

    /**
     * The table <code>database.offers_skills</code>.
     */
    public final OffersSkills OFFERS_SKILLS = com.talendorse.server.model.tables.OffersSkills.OFFERS_SKILLS;

    /**
     * The table <code>database.referrals</code>.
     */
    public final Referrals REFERRALS = com.talendorse.server.model.tables.Referrals.REFERRALS;

    /**
     * The table <code>database.skills</code>.
     */
    public final Skills SKILLS = com.talendorse.server.model.tables.Skills.SKILLS;

    /**
     * The table <code>database.tokens</code>.
     */
    public final Tokens TOKENS = com.talendorse.server.model.tables.Tokens.TOKENS;

    /**
     * The table <code>database.user_formation</code>.
     */
    public final UserFormation USER_FORMATION = com.talendorse.server.model.tables.UserFormation.USER_FORMATION;

    /**
     * The table <code>database.user_language</code>.
     */
    public final UserLanguage USER_LANGUAGE = com.talendorse.server.model.tables.UserLanguage.USER_LANGUAGE;

    /**
     * The table <code>database.users</code>.
     */
    public final Users USERS = com.talendorse.server.model.tables.Users.USERS;

    /**
     * The table <code>database.users_skills</code>.
     */
    public final UsersSkills USERS_SKILLS = com.talendorse.server.model.tables.UsersSkills.USERS_SKILLS;

    /**
     * The table <code>database.views_user</code>.
     */
    public final ViewsUser VIEWS_USER = com.talendorse.server.model.tables.ViewsUser.VIEWS_USER;

    /**
     * No further instances allowed
     */
    private Database() {
        super("database", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Companies.COMPANIES,
            Countries.COUNTRIES,
            Education.EDUCATION,
            Formations.FORMATIONS,
            Languages.LANGUAGES,
            OfferFormation.OFFER_FORMATION,
            Offers.OFFERS,
            OffersSkills.OFFERS_SKILLS,
            Referrals.REFERRALS,
            Skills.SKILLS,
            Tokens.TOKENS,
            UserFormation.USER_FORMATION,
            UserLanguage.USER_LANGUAGE,
            Users.USERS,
            UsersSkills.USERS_SKILLS,
            ViewsUser.VIEWS_USER);
    }
}
