/*
 * This file is generated by jOOQ.
 */
package com.talendorse.server.model;


import com.talendorse.server.model.tables.Companies;
import com.talendorse.server.model.tables.Countries;
import com.talendorse.server.model.tables.Education;
import com.talendorse.server.model.tables.Formations;
import com.talendorse.server.model.tables.Idioms;
import com.talendorse.server.model.tables.OfferFormation;
import com.talendorse.server.model.tables.Offers;
import com.talendorse.server.model.tables.OffersSkills;
import com.talendorse.server.model.tables.Referrals;
import com.talendorse.server.model.tables.Skills;
import com.talendorse.server.model.tables.Tokens;
import com.talendorse.server.model.tables.UserFormation;
import com.talendorse.server.model.tables.UserIdiom;
import com.talendorse.server.model.tables.Users;
import com.talendorse.server.model.tables.UsersSkills;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in database
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>database.companies</code>.
     */
    public static final Companies COMPANIES = com.talendorse.server.model.tables.Companies.COMPANIES;

    /**
     * The table <code>database.countries</code>.
     */
    public static final Countries COUNTRIES = com.talendorse.server.model.tables.Countries.COUNTRIES;

    /**
     * The table <code>database.education</code>.
     */
    public static final Education EDUCATION = com.talendorse.server.model.tables.Education.EDUCATION;

    /**
     * The table <code>database.formations</code>.
     */
    public static final Formations FORMATIONS = com.talendorse.server.model.tables.Formations.FORMATIONS;

    /**
     * The table <code>database.idioms</code>.
     */
    public static final Idioms IDIOMS = com.talendorse.server.model.tables.Idioms.IDIOMS;

    /**
     * The table <code>database.offer_formation</code>.
     */
    public static final OfferFormation OFFER_FORMATION = com.talendorse.server.model.tables.OfferFormation.OFFER_FORMATION;

    /**
     * The table <code>database.offers</code>.
     */
    public static final Offers OFFERS = com.talendorse.server.model.tables.Offers.OFFERS;

    /**
     * The table <code>database.offers_skills</code>.
     */
    public static final OffersSkills OFFERS_SKILLS = com.talendorse.server.model.tables.OffersSkills.OFFERS_SKILLS;

    /**
     * The table <code>database.referrals</code>.
     */
    public static final Referrals REFERRALS = com.talendorse.server.model.tables.Referrals.REFERRALS;

    /**
     * The table <code>database.skills</code>.
     */
    public static final Skills SKILLS = com.talendorse.server.model.tables.Skills.SKILLS;

    /**
     * The table <code>database.tokens</code>.
     */
    public static final Tokens TOKENS = com.talendorse.server.model.tables.Tokens.TOKENS;

    /**
     * The table <code>database.user_formation</code>.
     */
    public static final UserFormation USER_FORMATION = com.talendorse.server.model.tables.UserFormation.USER_FORMATION;

    /**
     * The table <code>database.user_idiom</code>.
     */
    public static final UserIdiom USER_IDIOM = com.talendorse.server.model.tables.UserIdiom.USER_IDIOM;

    /**
     * The table <code>database.users</code>.
     */
    public static final Users USERS = com.talendorse.server.model.tables.Users.USERS;

    /**
     * The table <code>database.users_skills</code>.
     */
    public static final UsersSkills USERS_SKILLS = com.talendorse.server.model.tables.UsersSkills.USERS_SKILLS;
}
